M48
; DRILL file KiCad 10.0.0 date 2026-05-13T20:08:07
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2026-05-13T20:08:07-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X111252Y-70612
X111252Y-123952
X184658Y-70612
X184658Y-123952
M30
